--Add initial role
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('ROLE_ADMIN', 'ADMIN Role');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('ROLE_JOB_SEEKER', 'Job Seeker');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('ROLE_RECRUITER', 'Recruiter');
INSERT INTO ROLE (ROLE_NAME, ROLE_DESCRIPTION) VALUES ('ROLE_EMPLOYER', 'Employeer');



